FROM node:alpine 
#node:16.3.0-alpine

WORKDIR /app

# RUN npm install -g @nestjs/cli
COPY package.json .
COPY package-lock.json .
RUN npm install --legacy-peer-deps
COPY . .

#RUN yarn migration:run

CMD ["yarn", "start:dev"]
